"""
Export trained DQN weights to rl/model_weights.js for game.html inference.

Usage:
    python rl/export_weights.py
    python rl/export_weights.py --model rl/models/checkpoint_100000.pth
"""

import argparse
import json
import sys
from pathlib import Path

import torch
import torch.nn as nn

sys.path.insert(0, str(Path(__file__).parent))
from model import DQN


def export(args):
    model_path = Path(args.model)
    if not model_path.exists():
        print(f"ERROR: {model_path} not found. Run training first.")
        sys.exit(1)

    net = DQN(input_dim=24, output_dim=4)
    net.load_state_dict(
        torch.load(model_path, map_location='cpu', weights_only=True)
    )
    net.eval()

    layers = []
    for module in net.net:
        if isinstance(module, nn.Linear):
            layers.append({
                'weight': module.weight.detach().tolist(),
                'bias':   module.bias.detach().tolist(),
            })

    out_path = Path(__file__).parent / 'model_weights.js'
    with open(out_path, 'w') as f:
        f.write('// Auto-generated by export_weights.py — do not edit\n')
        f.write('const RL_MODEL_WEIGHTS = ')
        json.dump({'layers': layers}, f, separators=(',', ':'))
        f.write(';\n')

    print(f"Exported {len(layers)} layers → {out_path}")
    for i, L in enumerate(layers):
        w = L['weight']
        print(f"  Layer {i}: {len(w[0])} → {len(w)}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--model', default='rl/models/best_model.pth',
        help='Path to model weights (.pth)'
    )
    export(parser.parse_args())
